### ISSUE TITLE
Support to Custom Extensions (DORA Metrics)

### ISSUE THREAD

**Issue by viniciusgabrielfo** [arcxp/datadog-service-catalog-metadata-provider#82]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the new native feature for DORA Metrics https://docs.datadoghq.com/dora_metrics/.

To filter the exactly paths for each service in a monorepo context, we should use a custom extension on Service Catalog: https://docs.datadoghq.com/dora_metrics/?tab=apicurl#filter-git-commits-in-monorepos

**Describe the solution you'd like**
Support to send Custom Extensions (https://docs.datadoghq.com/service_catalog/adding_metadata/#build-custom-extensions)

**Describe alternatives you've considered**
Just integrate directly Dora Extensions as an input, since it is a extension from Datadog itself.

Something similar we have for `integrations.pagerduty`, we could have something like `extensions.dora.url-patterns`

**Additional context**
![image](https://github.com/arcxp/datadog-service-catalog-metadata-provider/assets/33832090/1c09cb72-8d9b-4932-857d-cf0804b85f19)

**Comment by manchicken** [comment]
Ooooh, thanks! This looks like a really interesting addition. I'll see if I can dig in over the next couple of weeks.

**Comment by manchicken** [comment]
I added the extensions to the action. Can you try it out and see if it works?

**Comment by viniciusgabrielfo** [comment]
@manchicken with respect to the attribute being added to Service on Service Catalog seems to be working well, thanks!

I still haven't been able to make the DORA Metrics functionality work using this extension, but I think it falls outside this scope.

also, this feature will be added on `@v2.1` or `@v2.2`? For now I can only import if use `@main` right?

**Comment by manchicken** [comment]
This feature is available right now on the `@v2` tag. If you'd prefer to go to the specific version, that'd be `v2.3.0`.

**Comment by manchicken** [comment]
Confirmed closed.
